format = """
$directory\
$git_branch\
$battery\
$shlvl\
$line_break\
$character\
"""

add_newline = false

# Wait time(in ms) for starship to check files under the current directory.
scan_timeout = 10

[character]
success_symbol = '[Î»](bold green) '
error_symbol =   '[Î»](bold red) '

[[battery.display]]
threshold = 30
style = 'bold yellow'
[[battery.display]]
threshold = 20
style = 'bold red'

[directory]
truncation_length = 4
truncation_symbol = '.../'
#fish_style_pwd_dir_length = 1

[git_branch]
#symbol = 'ðŸŒ± '
#truncation_length = 7
#truncation_symbol = '...'
