#!/bin/bash

# Required to use VSCode marketplace instead of open-vsx.org
# TODO: Remove as soon as Microsoft considers this illegal :)
# https://github.com/microsoft/vscode/issues/31168
export VSCODE_GALLERY_SERVICE_URL='https://marketplace.visualstudio.com/_apis/public/gallery'
export VSCODE_GALLERY_CACHE_URL='https://vscode.blob.core.windows.net/gallery/index'
export VSCODE_GALLERY_ITEM_URL='https://marketplace.visualstudio.com/items'
export VSCODE_GALLERY_CONTROL_URL=''
export VSCODE_GALLERY_RECOMMENDATIONS_URL=''


~/apps/vscodium/bin/codium $@
