#!/bin/bash

PERC=$(light -G | sed 's/.[0-9]*$//')
DURATION=2000
ICON="$HOME/.config/icons/sun.svg"

./notify-send.sh "$PERC %" \
	--icon="$ICON" \
	--urgency=low \
	--expire-time="$DURATION" \
	--hint=int:value:"$PERC" \
	--replace=10
