#!/usr/bin/env bash

# shellcheck disable=SC2016
VOL=$(pactl list sinks | rg --only-matching '(\d+)%' -r '$1' | head -n 1)
#BAR=$(seq -s "─" $((VOL/5)) | sed 's/[0-9]//g')
DURATION=2000

if pactl list sinks | rg 'Mute: yes' -q; then
	ICON="$HOME/.config/icons/volume-x.svg"
else
	ICON="$HOME/.config/icons/volume-2.svg"
fi

./notify-send.sh "$VOL %" \
	--icon="$ICON" \
	--urgency=low \
	--expire-time="$DURATION" \
	--hint=int:value:"$VOL" \
	--replace=55
