#!/bin/bash

VAL=$(brightnessctl get)
MAX=$(brightnessctl max)
PERC=$(echo "scale=2; $VAL / $MAX * 100" | bc -l | sed 's/.[0-9]*$//')
DURATION=2000
ICON="$HOME/.config/icons/sun.svg"

./notify-send.sh "$PERC %" \
	--icon="$ICON" \
	--urgency=low \
	--expire-time="$DURATION" \
	--hint=int:value:"$PERC" \
	--replace=10
