#!/bin/sh
HLP="
Usage: open [file]
"
case "${1%%:*}" in
	http|https)
		exec firefox "$1"
		;;
	*.pdf|*.epub|*.mobi)
		exec zathura "$1"
		;;
	*.png|*.jpg|*.jpeg|*.svg)
		exec feh "$1"
		;;
	*.mp3|*.mp4)
		exec mpv "$1"
		;;
	-*)
		echo $HLP
		;;
	*)
		exec /usr/bin/xdg-open "$@"
		;;
esac
