#!/bin/bash


wifi_list() {
	#local WIFI_LIST='nmcli -f SSID,BARS,SECURITY,IN-USE'
	local WIFI_LIST='nmcli -f IN-USE,SSID device wifi'
	local SSID=$($WIFI_LIST | awk 'NR!=1')

	echo "$SSID"
}
export -f wifi_list

SSID=$(printf "$(wifi_list)" |\
	fzf\
	--bind 'ctrl-r:reload(nmcli device wifi rescan; printf "$(wifi_list)")'\
	--header 'Refresh with CTRL-R'\
	| sed 's/^\*//g' # trim the in-use character
)

if [ -z "$SSID" ]; then
	exit
fi

RESULT=$(nmcli device wifi connect $SSID)
if [ -z "$(echo $RESULT | grep Error)" ]; then
	echo Successfully connected to $SSID
	exit
fi

echo Attempting to provide credentials.
nmcli device wifi connect $SSID --ask
